"""Added features

Revision ID: da95438e93eb
Revises: 58aa3e4d2271
Create Date: 2021-06-22 21:52:21.474804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da95438e93eb'
down_revision = '58aa3e4d2271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild', sa.Column('country_rank_roles', sa.Boolean(), nullable=True))
    op.add_column('guild', sa.Column('guild_snipes', sa.Boolean(), nullable=True))
    op.add_column('guild', sa.Column('rank_roles', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild', 'rank_roles')
    op.drop_column('guild', 'guild_snipes')
    op.drop_column('guild', 'country_rank_roles')
    # ### end Alembic commands ###
