"""New db

Revision ID: 06b33d3a0b82
Revises: 
Create Date: 2021-08-16 06:15:46.108761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '06b33d3a0b82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beatmap',
                    sa.Column('id', mysql.VARCHAR(length=128), nullable=False),
                    sa.Column('name', mysql.VARCHAR(length=256), nullable=True),
                    sa.Column('description', mysql.VARCHAR(length=4096), nullable=True),
                    sa.Column('uploaded', mysql.DATETIME(), nullable=True),
                    sa.Column('automapper', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
                    sa.Column('ranked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
                    sa.Column('qualified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
                    sa.Column('uploader_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('uploader_name', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('uploader_hash', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('uploader_avatar', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('metadata_bpm', mysql.FLOAT(), nullable=True),
                    sa.Column('metadata_duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('metadata_song_name', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('metadata_song_sub_name', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('metadata_song_author_name', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('metadata_level_author_name', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('stats_plays', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('stats_downloads', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('stats_upvotes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('stats_downvotes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('stats_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mariadb_default_charset='utf32',
                    mariadb_engine='InnoDB'
                    )
    op.create_table('member_role',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('guild_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
                    sa.Column('member_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
                    sa.Column('role_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], name='member_role_ibfk_1'),
                    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name='member_role_ibfk_2'),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='member_role_ibfk_3'),
                    sa.PrimaryKeyConstraint('id'),
                    mariadb_default_charset='utf32',
                    mariadb_engine='InnoDB'
                    )
    op.create_table('member',
                    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
                    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mariadb_default_charset='utf32',
                    mariadb_engine='InnoDB'
                    )
    op.create_table('channel',
                    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
                    sa.Column('guild_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
                    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
                    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], name='channel_ibfk_1', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    mariadb_default_charset='utf32',
                    mariadb_engine='InnoDB'
                    )
    op.create_table('achievement_role_member',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('guild_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
                    sa.Column('member_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
                    sa.Column('achievement_role_id', mysql.INTEGER(display_width=11), autoincrement=False,
                              nullable=True),
                    sa.ForeignKeyConstraint(['achievement_role_id'], ['achievement_role.id'],
                                            name='achievement_role_member_ibfk_3'),
                    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], name='achievement_role_member_ibfk_1'),
                    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name='achievement_role_member_ibfk_2'),
                    sa.PrimaryKeyConstraint('id'),
                    mariadb_default_charset='utf32',
                    mariadb_engine='InnoDB'
                    )
    op.create_table('achievement_role',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('guild_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
                    sa.Column('role_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
                    sa.Column('group', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('identifier', mysql.VARCHAR(length=128), nullable=True),
                    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], name='achievement_role_ibfk_1',
                                            ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='achievement_role_ibfk_2',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    mariadb_default_charset='utf32',
                    mariadb_engine='InnoDB'
                    )
    op.create_table('guild_player',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('guild_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
                    sa.Column('member_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
                    sa.Column('player_id', mysql.VARCHAR(length=128), nullable=True),
                    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], name='guild_player_ibfk_1'),
                    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name='guild_player_ibfk_2'),
                    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name='guild_player_ibfk_3'),
                    sa.PrimaryKeyConstraint('id'),
                    mariadb_default_charset='utf32',
                    mariadb_engine='InnoDB'
                    )
    op.create_table('setting',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('guild_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
                    sa.Column('setting_type', mysql.ENUM('INT', 'STRING', 'BOOLEAN'), nullable=True),
                    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('value', mysql.VARCHAR(length=1024), nullable=True),
                    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], name='setting_ibfk_1', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    mariadb_default_charset='utf32',
                    mariadb_engine='InnoDB'
                    )
    op.create_table('score',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('player_id', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('rank', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('score_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('unmodified_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('mods', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('pp', mysql.FLOAT(), nullable=True),
                    sa.Column('weight', mysql.FLOAT(), nullable=True),
                    sa.Column('time_set', mysql.DATETIME(), nullable=True),
                    sa.Column('leaderboard_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('song_hash', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('song_name', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('song_sub_name', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('song_author_name', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('level_author_name', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('characteristic',
                              mysql.ENUM('STANDARD', 'ONE_SABER', 'NO_ARROWS', 'DEGREE_90', 'DEGREE_360', 'LIGHTSHOW',
                                         'LAWLESS', 'UNKNOWN'), nullable=True),
                    sa.Column('difficulty', mysql.ENUM('EASY', 'NORMAL', 'HARD', 'EXPERT', 'EXPERT_PLUS', 'UNKNOWN'),
                              nullable=True),
                    sa.Column('max_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name='score_ibfk_1', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    mariadb_default_charset='utf32',
                    mariadb_engine='InnoDB'
                    )
    op.create_table('guild',
                    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
                    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mariadb_default_charset='utf32',
                    mariadb_engine='InnoDB'
                    )
    op.create_table('guild_member',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('guild_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
                    sa.Column('member_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], name='guild_member_ibfk_1'),
                    sa.ForeignKeyConstraint(['member_id'], ['member.id'], name='guild_member_ibfk_2'),
                    sa.PrimaryKeyConstraint('id'),
                    mariadb_default_charset='utf32',
                    mariadb_engine='InnoDB'
                    )
    op.create_table('player',
                    sa.Column('id', mysql.VARCHAR(length=128), nullable=False),
                    sa.Column('player_name', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('avatar', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('rank', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('country_rank', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('pp', mysql.FLOAT(), nullable=True),
                    sa.Column('country', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('role', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('badges', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
                    sa.Column('history', mysql.VARCHAR(length=512), nullable=True),
                    sa.Column('permissions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('inactive', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('banned', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    mariadb_default_charset='utf32',
                    mariadb_engine='InnoDB'
                    )
    op.create_table('sent_score',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('score_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('guild_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], name='sent_score_ibfk_2'),
                    sa.ForeignKeyConstraint(['score_id'], ['score.id'], name='sent_score_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mariadb_default_charset='utf32',
                    mariadb_engine='InnoDB'
                    )
    op.create_table('beatmap_version_difficulty',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('version_hash', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('njs', mysql.FLOAT(), nullable=True),
                    sa.Column('offset', mysql.FLOAT(), nullable=True),
                    sa.Column('notes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('bombs', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('obstacles', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('nps', mysql.FLOAT(), nullable=True),
                    sa.Column('length', mysql.FLOAT(), nullable=True),
                    sa.Column('characteristic',
                              mysql.ENUM('STANDARD', 'ONE_SABER', 'NO_ARROWS', 'DEGREE_90', 'DEGREE_360', 'LIGHTSHOW',
                                         'LAWLESS', 'UNKNOWN'), nullable=True),
                    sa.Column('difficulty', mysql.ENUM('EASY', 'NORMAL', 'HARD', 'EXPERT', 'EXPERT_PLUS', 'UNKNOWN'),
                              nullable=True),
                    sa.Column('events', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('chroma', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
                    sa.Column('me', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
                    sa.Column('ne', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
                    sa.Column('cinema', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
                    sa.Column('seconds', mysql.FLOAT(), nullable=True),
                    sa.Column('parity_errors', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('parity_warns', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('parity_resets', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['version_hash'], ['beatmap_version.hash'],
                                            name='beatmap_version_difficulty_ibfk_1', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    mariadb_default_charset='utf32',
                    mariadb_engine='InnoDB'
                    )
    op.create_table('beatmap_version',
                    sa.Column('hash', mysql.VARCHAR(length=128), nullable=False),
                    sa.Column('map_id', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('key', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('state', mysql.VARCHAR(length=128), nullable=True),
                    sa.Column('created_at', mysql.DATETIME(), nullable=True),
                    sa.Column('sage_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
                    sa.Column('download_url', mysql.VARCHAR(length=256), nullable=True),
                    sa.Column('cover_url', mysql.VARCHAR(length=256), nullable=True),
                    sa.Column('preview_url', mysql.VARCHAR(length=256), nullable=True),
                    sa.ForeignKeyConstraint(['map_id'], ['beatmap.id'], name='beatmap_version_ibfk_1',
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('hash'),
                    mariadb_default_charset='utf32',
                    mariadb_engine='InnoDB'
                    )
    op.create_table('role',
                    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
                    sa.Column('guild_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
                    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
                    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], name='role_ibfk_1', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    mariadb_default_charset='utf32',
                    mariadb_engine='InnoDB'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    op.drop_table('beatmap_version')
    op.drop_table('beatmap_version_difficulty')
    op.drop_table('sent_score')
    op.drop_table('player')
    op.drop_table('guild_member')
    op.drop_table('guild')
    op.drop_table('score')
    op.drop_table('setting')
    op.drop_table('guild_player')
    op.drop_table('achievement_role')
    op.drop_table('achievement_role_member')
    op.drop_table('channel')
    op.drop_table('member')
    op.drop_table('member_role')
    op.drop_table('beatmap')
    # ### end Alembic commands ###
