"""Twitch Cog

Revision ID: 2ca0df756981
Revises: 73ed4b550356
Create Date: 2022-06-10 01:31:46.544819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca0df756981'
down_revision = '73ed4b550356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitch_broadcaster',
    sa.Column('id', sa.String(length=128), autoincrement=False, nullable=False),
    sa.Column('login', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('profile_image_url', sa.String(length=256), nullable=True),
    sa.Column('broadcaster_type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guild_twitch_broadcaster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('member_id', sa.BigInteger(), nullable=True),
    sa.Column('twitch_broadcaster_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guild.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['twitch_broadcaster_id'], ['twitch_broadcaster.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild_twitch_broadcaster')
    op.drop_table('twitch_broadcaster')
    # ### end Alembic commands ###
