"""DateTime fileds to Timestamps

Revision ID: 42844d330e75
Revises: 26478de04700
Create Date: 2022-04-07 18:34:01.326490

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '42844d330e75'
down_revision = '26478de04700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("beatmap", "uploaded", existing_type=sa.DATETIME, type_=sa.TIMESTAMP)
    op.alter_column("beatmap_version", "created_at", existing_type=sa.DATETIME, type_=sa.TIMESTAMP)
    op.alter_column("leaderboard", "created_date", existing_type=sa.DATETIME, type_=sa.TIMESTAMP)
    op.alter_column("leaderboard", "ranked_date", existing_type=sa.DATETIME, type_=sa.TIMESTAMP)
    op.alter_column("leaderboard", "qualified_date", existing_type=sa.DATETIME, type_=sa.TIMESTAMP)
    op.alter_column("leaderboard", "loved_date", existing_type=sa.DATETIME, type_=sa.TIMESTAMP)
    op.alter_column("score", "time_set", existing_type=sa.DATETIME, type_=sa.TIMESTAMP)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("beatmap", "uploaded", type_=sa.DATETIME, existing_type=sa.TIMESTAMP)
    op.alter_column("beatmap_version", "created_at", type_=sa.DATETIME, existing_type=sa.TIMESTAMP)
    op.alter_column("leaderboard", "created_date", type_=sa.DATETIME, existing_type=sa.TIMESTAMP)
    op.alter_column("leaderboard", "ranked_date", type_=sa.DATETIME, existing_type=sa.TIMESTAMP)
    op.alter_column("leaderboard", "qualified_date", type_=sa.DATETIME, existing_type=sa.TIMESTAMP)
    op.alter_column("leaderboard", "loved_date", type_=sa.DATETIME, existing_type=sa.TIMESTAMP)
    op.alter_column("score", "time_set", type_=sa.DATETIME, existing_type=sa.TIMESTAMP)
    # ### end Alembic commands ###
