"""Additional fields

Revision ID: 73ed4b550356
Revises: 42844d330e75
Create Date: 2022-06-10 01:29:31.690016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73ed4b550356'
down_revision = '42844d330e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('beatmap', 'uploaded',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('beatmap_version', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('leaderboard', 'created_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('leaderboard', 'ranked_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('leaderboard', 'qualified_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('leaderboard', 'loved_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('member_role_ibfk_3', 'member_role', type_='foreignkey')
    op.create_foreign_key(None, 'member_role', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.alter_column('score', 'time_set',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('score', 'time_set',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'member_role', type_='foreignkey')
    op.create_foreign_key('member_role_ibfk_3', 'member_role', 'role', ['role_id'], ['id'])
    op.alter_column('leaderboard', 'loved_date',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('leaderboard', 'qualified_date',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('leaderboard', 'ranked_date',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('leaderboard', 'created_date',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('beatmap_version', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('beatmap', 'uploaded',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
