"""added created_at metadata columns

Revision ID: 88862c10b553
Revises: 2ca0df756981
Create Date: 2023-03-16 22:09:28.093150

"""
from datetime import datetime, timedelta

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '88862c10b553'
down_revision = '2ca0df756981'
branch_labels = None
depends_on = None


def upgrade():
    outdated = (datetime.today() - timedelta(days=365)).isoformat()

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beatmap', sa.Column('cached_at', sa.DateTime(timezone=True), nullable=True))
    op.execute(f"UPDATE beatmap SET cached_at = '{outdated}' WHERE cached_at IS NULL")
    op.alter_column('beatmap', 'cached_at', existing_type=sa.DateTime(timezone=True), nullable=False)

    op.add_column('beatmap_version', sa.Column('cached_at', sa.DateTime(timezone=True), nullable=True))
    op.execute(f"UPDATE beatmap_version SET cached_at = '{outdated}' WHERE cached_at IS NULL")
    op.alter_column('beatmap_version', 'cached_at', existing_type=sa.DateTime(timezone=True), nullable=False)

    op.add_column('beatmap_version_difficulty', sa.Column('cached_at', sa.DateTime(timezone=True), nullable=True))
    op.execute(f"UPDATE beatmap_version_difficulty SET cached_at = '{outdated}' WHERE cached_at IS NULL")
    op.alter_column('beatmap_version_difficulty', 'cached_at', existing_type=sa.DateTime(timezone=True), nullable=False)

    op.add_column('leaderboard', sa.Column('cached_at', sa.DateTime(timezone=True), nullable=True))
    op.execute(f"UPDATE leaderboard SET cached_at = '{outdated}' WHERE cached_at IS NULL")
    op.alter_column('leaderboard', 'cached_at', existing_type=sa.DateTime(timezone=True), nullable=False)

    op.add_column('message', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.execute(f"UPDATE message SET created_at = '{outdated}' WHERE created_at IS NULL")
    op.alter_column('message', 'created_at', existing_type=sa.DateTime(timezone=True), nullable=False)

    op.add_column('message_view', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.execute(f"UPDATE message_view SET created_at = '{outdated}' WHERE created_at IS NULL")
    op.alter_column('message_view', 'created_at', existing_type=sa.DateTime(timezone=True), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_view', 'created_at')
    op.drop_column('message', 'created_at')
    op.drop_column('leaderboard', 'cached_at')
    op.drop_column('beatmap_version_difficulty', 'cached_at')
    op.drop_column('beatmap_version', 'cached_at')
    op.drop_column('beatmap', 'cached_at')
    # ### end Alembic commands ###
