"""Added new setting types

Revision ID: a52babf8eefa
Revises: 4f7f2589381d
Create Date: 2022-03-07 18:15:12.378487

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a52babf8eefa'
down_revision = '4f7f2589381d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE `setting` MODIFY COLUMN `setting_type` enum( 'INT','STRING','BOOLEAN','CHANNEL','EMOJI' ) NOT NULL AFTER `guild_id`;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE `setting` MODIFY COLUMN `setting_type` enum( 'INT', 'STRING', 'BOOLEAN' ) NOT NULL AFTER `guild_id`;")
    # ### end Alembic commands ###
